<DocEditView>:
    toolbar: toolbar
    text_edit: text_edit

    text: ""

    orientation: 'vertical'
    canvas.before:
        Clear:
        Color:
            rgba: (.9, .9, .9, 1)  # app.theme_cls.bg_light  # doesn't work
        Rectangle:
            pos: self.pos
            size: self.size

    NativoToolbar:
        id: toolbar
        left_action_items: [['menu', lambda x: root.nav_drawer.set_state("open")]]

    TextEdit:
        id: text_edit