"""Initial schema with user roles and language colors

Revision ID: a526a9c4cfb3
Revises: 
Create Date: 2025-11-01 22:43:06.082172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a526a9c4cfb3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('native_name', sa.String(length=255), nullable=True),
    sa.Column('iso_639_3', sa.String(length=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_endangered', sa.Boolean(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('background_color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_iso_639_3'), 'languages', ['iso_639_3'], unique=True)
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'NATIVE_SPEAKER', 'RESEARCHER', 'PUBLIC', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Enum('STORY', 'HISTORICAL_RECORD', 'BOOK', 'ARTICLE', 'TRANSCRIPTION', 'DEFINITION', 'LITERAL_TRANSLATION', 'CONTEXT_NOTE', 'USAGE_EXAMPLE', 'ETYMOLOGY', 'CULTURAL_SIGNIFICANCE', 'TRANSLATION', 'NOTE', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_language_id'), 'documents', ['language_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('romanization', sa.String(length=255), nullable=True),
    sa.Column('ipa_pronunciation', sa.String(length=255), nullable=True),
    sa.Column('part_of_speech', sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PRONOUN', 'PREPOSITION', 'CONJUNCTION', 'INTERJECTION', 'ARTICLE', 'DETERMINER', 'PARTICLE', 'NUMERAL', 'CLASSIFIER', 'OTHER', name='partofspeech'), nullable=True),
    sa.Column('gender', sa.Enum('MASCULINE', 'FEMININE', 'NEUTER', 'COMMON', 'ANIMATE', 'INANIMATE', 'NOT_APPLICABLE', name='grammaticalgender'), nullable=True),
    sa.Column('plurality', sa.Enum('SINGULAR', 'PLURAL', 'DUAL', 'TRIAL', 'PAUCAL', 'COLLECTIVE', 'NOT_APPLICABLE', name='plurality'), nullable=True),
    sa.Column('grammatical_case', sa.Enum('NOMINATIVE', 'ACCUSATIVE', 'GENITIVE', 'DATIVE', 'ABLATIVE', 'LOCATIVE', 'INSTRUMENTAL', 'VOCATIVE', 'PARTITIVE', 'COMITATIVE', 'ESSIVE', 'TRANSLATIVE', 'ERGATIVE', 'ABSOLUTIVE', 'NOT_APPLICABLE', 'OTHER', name='grammaticalcase'), nullable=True),
    sa.Column('verb_aspect', sa.Enum('PERFECTIVE', 'IMPERFECTIVE', 'PROGRESSIVE', 'CONTINUOUS', 'HABITUAL', 'ITERATIVE', 'INCHOATIVE', 'PERFECT', 'PROSPECTIVE', 'NOT_APPLICABLE', 'OTHER', name='verbaspect'), nullable=True),
    sa.Column('animacy', sa.Enum('ANIMATE', 'INANIMATE', 'HUMAN', 'NON_HUMAN', 'PERSONAL', 'IMPERSONAL', 'NOT_APPLICABLE', name='animacy'), nullable=True),
    sa.Column('register', sa.Enum('FORMAL', 'INFORMAL', 'COLLOQUIAL', 'SLANG', 'CEREMONIAL', 'ARCHAIC', 'TABOO', 'POETIC', 'TECHNICAL', 'NEUTRAL', name='register'), nullable=True),
    sa.Column('confirmed_at_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'DEPRECATED', 'ARCHIVED', name='wordstatus'), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_at_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_is_verified'), 'words', ['is_verified'], unique=False)
    op.create_index(op.f('ix_words_language_id'), 'words', ['language_id'], unique=False)
    op.create_index(op.f('ix_words_part_of_speech'), 'words', ['part_of_speech'], unique=False)
    op.create_index(op.f('ix_words_romanization'), 'words', ['romanization'], unique=False)
    op.create_index(op.f('ix_words_status'), 'words', ['status'], unique=False)
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=False)
    op.create_table('word_antonyms',
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('antonym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['antonym_id'], ['words.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'antonym_id')
    )
    op.create_table('word_audio',
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('audio_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audio.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'audio_id')
    )
    op.create_table('word_documents',
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('DEFINITION', 'LITERAL_TRANSLATION', 'CONTEXT_NOTE', 'USAGE_EXAMPLE', 'ETYMOLOGY', 'CULTURAL_SIGNIFICANCE', 'OTHER', name='worddocumenttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'document_id', 'relationship_type')
    )
    op.create_table('word_image',
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'image_id')
    )
    op.create_table('word_related',
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('related_word_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_word_id'], ['words.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'related_word_id')
    )
    op.create_table('word_synonyms',
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('synonym_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['synonym_id'], ['words.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'synonym_id')
    )
    op.create_table('word_tags',
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('word_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_tags')
    op.drop_table('word_synonyms')
    op.drop_table('word_related')
    op.drop_table('word_image')
    op.drop_table('word_documents')
    op.drop_table('word_audio')
    op.drop_table('word_antonyms')
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_index(op.f('ix_words_status'), table_name='words')
    op.drop_index(op.f('ix_words_romanization'), table_name='words')
    op.drop_index(op.f('ix_words_part_of_speech'), table_name='words')
    op.drop_index(op.f('ix_words_language_id'), table_name='words')
    op.drop_index(op.f('ix_words_is_verified'), table_name='words')
    op.drop_table('words')
    op.drop_table('images')
    op.drop_index(op.f('ix_documents_language_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('audio')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('locations')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_index(op.f('ix_languages_iso_639_3'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###

