"""add_user_language_relationship

Revision ID: c737f73cccf6
Revises: 0824d0747660
Create Date: 2025-11-02 08:37:29.751502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c737f73cccf6'
down_revision: Union[str, None] = '0824d0747660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_languages',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level', sa.Enum('NATIVE', 'FLUENT', 'INTERMEDIATE', 'BEGINNER', name='proficiencylevel'), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_verify', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'language_id')
    )
    # Note: Removed ALTER COLUMN commands as SQLite doesn't support them
    # All tables already have UUID columns in the correct format
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_languages')
    # Note: Removed ALTER COLUMN commands as SQLite doesn't support them
    # ### end Alembic commands ###

